/*
 * ConfigurationJoueur.java
 *
 * Created on 10 février 2002, 18:50
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.Vector;
/**
 *
 * @author  Administrateur
 */
public class ConfigurationJoueur extends javax.swing.JPanel {
    private JTabbedPane aPane;
    private Initialisation aInit;
    
    private int aIndex;
    private String aCouleur;
    private boolean aChangeCouleur;
    
    private Proprietaire aProprietaire;
    
    /** Creates new form ConfigurationJoueur */
    public ConfigurationJoueur() {
        initComponents();
        
        aProprietaire = new Proprietaire();
        //					   Atk   Def   Prod  Vit   Int
        aComboRace.addItem(new Race("Federation" , 1.20, 0.60, 1.00, 4.00, 1.25));
        aComboRace.addItem(new Race("Vulcain"    , 0.75, 0.75, 2.00, 1.00, 2.00));
        aComboRace.addItem(new Race("Klingon"    , 2.50, 0.50, 1.00, 2.00, 0.75));
        aComboRace.addItem(new Race("The Borg"   , 2.00, 2.00, 2.00, 2.00, 0.00));
        aComboRace.addItem(new Race("Batards"    , 5.50));
        
        aChangeCouleur = false;
    }
    
    public void paint(Graphics pGraphics) {
        super.paint(pGraphics);
        
        pGraphics.setColor(Color.black);
        pGraphics.drawRect(140, 153, 100, 10);
        pGraphics.drawRect(140, 173, 100, 10);
        pGraphics.drawRect(140, 193, 100, 10);
        pGraphics.drawRect(140, 213, 100, 10);
        pGraphics.drawRect(140, 233, 100, 10);
        
        Race lRace = (Race)aComboRace.getSelectedItem();
        // double lNorme = lRace.reqNorme();
        double lNorme = lRace.reqMax();
        
        pGraphics.setColor(Color.red);
        pGraphics.fillRect(141, 154, (int)(lRace.reqAttaque()/lNorme * 99), 9);
        pGraphics.fillRect(141, 174, (int)(lRace.reqDefense()/lNorme * 99), 9);
        pGraphics.fillRect(141, 194, (int)(lRace.reqProduction()/lNorme * 99), 9);
        pGraphics.fillRect(141, 214, (int)(lRace.reqDeplacement()/lNorme * 99), 9);
        pGraphics.fillRect(141, 234, (int)(lRace.reqIntelligence()/lNorme * 99), 9);
        
        // aLabelNorme.setText("Norme : " + lRace.reqNorme());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        aZoneTexteNom = new javax.swing.JTextField();
        aComboCouleur = new javax.swing.JComboBox();
        aComboRace = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        aBoutonDecAttaque = new javax.swing.JButton();
        aBoutonDecDefense = new javax.swing.JButton();
        aBoutonDecProduction = new javax.swing.JButton();
        aBoutonDecDeplacement = new javax.swing.JButton();
        aBoutonIncAttaque = new javax.swing.JButton();
        aBoutonIncDefense = new javax.swing.JButton();
        aBoutonIncProduction = new javax.swing.JButton();
        aBoutonIncDeplacement = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        aBoutonDecIntelligence = new javax.swing.JButton();
        aBoutonIncIntelligence = new javax.swing.JButton();
        
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        aZoneTexteNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aZoneTexteNomActionPerformed(evt);
            }
        });
        
        add(aZoneTexteNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 140, 20));
        
        aComboCouleur.setMaximumRowCount(6);
        aComboCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aComboCouleurActionPerformed(evt);
            }
        });
        
        add(aComboCouleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, -1));
        
        aComboRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aComboRaceActionPerformed(evt);
            }
        });
        
        add(aComboRace, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, -1));
        
        jLabel1.setText("Nom");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 20));
        
        jLabel3.setText("Couleur");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 30));
        
        jLabel5.setText("Race");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));
        
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, 10));
        
        jLabel6.setText("Attaque");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, -1));
        
        jLabel7.setText("Defense");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, -1));
        
        jLabel8.setText("Production");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, -1));
        
        jLabel9.setText("Deplacement");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 100, -1));
        
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 10, 100));
        
        aBoutonDecAttaque.setPreferredSize(new java.awt.Dimension(20, 20));
        aBoutonDecAttaque.setMaximumSize(new java.awt.Dimension(20, 20));
        aBoutonDecAttaque.setMinimumSize(new java.awt.Dimension(20, 20));
        aBoutonDecAttaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBoutonDecAttaqueActionPerformed(evt);
            }
        });
        
        add(aBoutonDecAttaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 20, 20));
        
        aBoutonDecDefense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBoutonDecDefenseActionPerformed(evt);
            }
        });
        
        add(aBoutonDecDefense, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 20, 20));
        
        aBoutonDecProduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBoutonDecProductionActionPerformed(evt);
            }
        });
        
        add(aBoutonDecProduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 20, 20));
        
        aBoutonDecDeplacement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBoutonDecDeplacementActionPerformed(evt);
            }
        });
        
        add(aBoutonDecDeplacement, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 20, 20));
        
        aBoutonIncAttaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBoutonIncAttaqueActionPerformed(evt);
            }
        });
        
        add(aBoutonIncAttaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 20, 20));
        
        aBoutonIncDefense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBoutonIncDefenseActionPerformed(evt);
            }
        });
        
        add(aBoutonIncDefense, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 20, 20));
        
        aBoutonIncProduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBoutonIncProductionActionPerformed(evt);
            }
        });
        
        add(aBoutonIncProduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 20, 20));
        
        aBoutonIncDeplacement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBoutonIncDeplacementActionPerformed(evt);
            }
        });
        
        add(aBoutonIncDeplacement, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 20, 20));
        
        jLabel2.setText("Intelligence");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, 20));
        
        add(aBoutonDecIntelligence, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 20, 20));
        
        add(aBoutonIncIntelligence, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 20, 20));
        
    }//GEN-END:initComponents
    
    private void aComboCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aComboCouleurActionPerformed
        if (!aChangeCouleur) {
            String lAncienneCouleur = aCouleur;
            aCouleur = (String)aComboCouleur.getSelectedItem();
            if (aCouleur != lAncienneCouleur) {
                aProprietaire.asgnCouleur(aInit.utiliseCouleur(aCouleur, lAncienneCouleur));
                aInit.reafficheCouleurs();
            }
        }
    }//GEN-LAST:event_aComboCouleurActionPerformed
    
    private void aZoneTexteNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aZoneTexteNomActionPerformed
        String lNom = aZoneTexteNom.getText();
        aPane.setTitleAt(aIndex, lNom);
        aProprietaire.asgnNom(lNom);
    }//GEN-LAST:event_aZoneTexteNomActionPerformed

    private void aBoutonIncIntelligenceActionPerformed(java.awt.event.ActionEvent evt) {
            ((Race)aComboRace.getSelectedItem()).incIntelligence();
            repaint();
    }
    
    private void aBoutonIncDeplacementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBoutonIncDeplacementActionPerformed
        ((Race)aComboRace.getSelectedItem()).incDeplacement();
        repaint();
    }//GEN-LAST:event_aBoutonIncDeplacementActionPerformed
    
    private void aBoutonIncProductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBoutonIncProductionActionPerformed
        ((Race)aComboRace.getSelectedItem()).incProduction();
        repaint();
    }//GEN-LAST:event_aBoutonIncProductionActionPerformed
    
    private void aBoutonIncDefenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBoutonIncDefenseActionPerformed
        ((Race)aComboRace.getSelectedItem()).incDefense();
        repaint();
    }//GEN-LAST:event_aBoutonIncDefenseActionPerformed
    
    private void aBoutonIncAttaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBoutonIncAttaqueActionPerformed
        ((Race)aComboRace.getSelectedItem()).incAttaque();
        repaint();
    }//GEN-LAST:event_aBoutonIncAttaqueActionPerformed
    
    private void aBoutonDecIntelligenceActionPerformed(java.awt.event.ActionEvent evt) {
        ((Race)aComboRace.getSelectedItem()).decIntelligence();
        repaint();
    }
    
    private void aBoutonDecDeplacementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBoutonDecDeplacementActionPerformed
            ((Race)aComboRace.getSelectedItem()).decDeplacement();
            repaint();
    }//GEN-LAST:event_aBoutonDecDeplacementActionPerformed
    
    private void aBoutonDecProductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBoutonDecProductionActionPerformed
        ((Race)aComboRace.getSelectedItem()).decProduction();
        repaint();
    }//GEN-LAST:event_aBoutonDecProductionActionPerformed
    
    private void aBoutonDecDefenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBoutonDecDefenseActionPerformed
        ((Race)aComboRace.getSelectedItem()).decDefense();
        repaint();
    }//GEN-LAST:event_aBoutonDecDefenseActionPerformed
    
    private void aBoutonDecAttaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBoutonDecAttaqueActionPerformed
        ((Race)aComboRace.getSelectedItem()).decAttaque();
        repaint();
    }//GEN-LAST:event_aBoutonDecAttaqueActionPerformed
    
    private void aComboRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aComboRaceActionPerformed
        aProprietaire.asgnRace((Race)aComboRace.getSelectedItem());
        boolean lValeur = ((Race)aComboRace.getSelectedItem()).reqModifiable();
        
        aBoutonIncAttaque.setEnabled(lValeur);
        aBoutonIncDefense.setEnabled(lValeur);
        aBoutonIncProduction.setEnabled(lValeur);
        aBoutonIncDeplacement.setEnabled(lValeur);
        aBoutonIncIntelligence.setEnabled(lValeur);
        
        aBoutonDecAttaque.setEnabled(lValeur);
        aBoutonDecDefense.setEnabled(lValeur);
        aBoutonDecProduction.setEnabled(lValeur);
        aBoutonDecDeplacement.setEnabled(lValeur);
        aBoutonDecIntelligence.setEnabled(lValeur);
        
        repaint();
    }//GEN-LAST:event_aComboRaceActionPerformed
    
    public void asgnPaneEtOwner(JTabbedPane pPane, Initialisation pInit) {
        aPane = pPane;
        aInit = pInit;
        
        aIndex = pPane.getTabCount();
        aProprietaire.asgnNom("Joueur " + (aIndex));
        
        aZoneTexteNom.setText(aProprietaire.reqNom());
        pPane.addTab(aProprietaire.reqNom(), this);
        
        reinitialiseChoixCouleurs();
    }
    
    public void reinitialiseChoixCouleurs() {
        aChangeCouleur = true;
        aComboCouleur.removeAllItems();
        if (aCouleur != null) aComboCouleur.addItem(aCouleur);
        
        Vector lVecteur = aInit.reqCouleursLibres();
        for (int i = 0; i<lVecteur.size(); ++i) {
            aComboCouleur.addItem(lVecteur.get(i));
        }
        
        if (aCouleur == null) {
            String lAncienneCouleur = aCouleur;
            aCouleur = (String)lVecteur.get(0);
            aProprietaire.asgnCouleur(aInit.utiliseCouleur(aCouleur, lAncienneCouleur));
        }
        
        aChangeCouleur = false;
    }
    
    public void relacheCouleur() {
        aInit.utiliseCouleur(null, aCouleur);
    }
    
    public Proprietaire reqProprietaire() {
        return aProprietaire;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aZoneTexteNom;
    private javax.swing.JComboBox aComboCouleur;
    private javax.swing.JComboBox aComboRace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton aBoutonDecAttaque;
    private javax.swing.JButton aBoutonDecDefense;
    private javax.swing.JButton aBoutonDecProduction;
    private javax.swing.JButton aBoutonDecDeplacement;
    private javax.swing.JButton aBoutonIncAttaque;
    private javax.swing.JButton aBoutonIncDefense;
    private javax.swing.JButton aBoutonIncProduction;
    private javax.swing.JButton aBoutonIncDeplacement;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton aBoutonDecIntelligence;
    private javax.swing.JButton aBoutonIncIntelligence;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String args[]) {
        JFrame lApplication = new JFrame("Espace MiniGame");
        
        ConfigurationJoueur lConfig = new ConfigurationJoueur();
        lApplication.getContentPane().add(lConfig, BorderLayout.CENTER);
        lApplication.addWindowListener
        (
        new WindowAdapter() {
            public void windowClosing(WindowEvent pEvenement) {
                System.exit(0);
            }
        }
        );
        
        lApplication.setSize(290, 265);
        lApplication.show();
    }
}
