/*
 * ConfigurationEspace.java
 *
 * Created on 11 février 2002, 19:49
 */

/**
 *
 * @author  Administrateur
 */
public class ConfigurationEspace extends javax.swing.JPanel {
    private Initialisation aInit;
    private int aNbJoueur;
    
    /** Creates new form ConfigurationEspace */
    public ConfigurationEspace() {
        initComponents();
    }
    
    public void asgnInitialisation(Initialisation pInit) {
        aInit = pInit;
    }
    
    public void asgnNbJoueur(int pNbJoueur) {
        aNbJoueur = pNbJoueur;
        
        if (Integer.parseInt(aLabelPlanete.getText()) < (4 * aNbJoueur)) {
            // Le nb de planète est trop petit..
            aLabelPlanete.setText(""+(4*aNbJoueur));
            aZoneTextePlanete.setText(aLabelPlanete.getText());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        aLabelQPlanete = new javax.swing.JLabel();
        aZoneTextePlanete = new javax.swing.JTextField();
        aLabelPlanete = new javax.swing.JLabel();
        aLabelQEtoiles = new javax.swing.JLabel();
        aZoneTexteEtoiles = new javax.swing.JTextField();
        aLabelEtoiles = new javax.swing.JLabel();
        aLabelQVitesse = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        aZoneTexteVitesse = new javax.swing.JTextField();
        aLabelVitesse = new javax.swing.JLabel();
        
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        aLabelQPlanete.setText("Nb Planete");
        add(aLabelQPlanete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 20));
        
        aZoneTextePlanete.setText("8");
        aZoneTextePlanete.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        aZoneTextePlanete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aZoneTextePlaneteActionPerformed(evt);
            }
        });
        
        add(aZoneTextePlanete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, -1));
        
        aLabelPlanete.setText("8");
        aLabelPlanete.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        add(aLabelPlanete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 40, 20));
        
        aLabelQEtoiles.setText("Nb Etoiles");
        add(aLabelQEtoiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 20));
        
        aZoneTexteEtoiles.setText("300");
        aZoneTexteEtoiles.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        aZoneTexteEtoiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aZoneTexteEtoilesActionPerformed(evt);
            }
        });
        
        add(aZoneTexteEtoiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 90, 20));
        
        aLabelEtoiles.setText("300");
        aLabelEtoiles.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        add(aLabelEtoiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 40, 20));
        
        aLabelQVitesse.setText("Interval (ms)");
        add(aLabelQVitesse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 20));
        
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 10));
        
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 260, 10));
        
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, 10));
        
        aZoneTexteVitesse.setText("50");
        aZoneTexteVitesse.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        aZoneTexteVitesse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aZoneTexteVitesseActionPerformed(evt);
            }
        });
        
        add(aZoneTexteVitesse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 90, -1));
        
        aLabelVitesse.setText("50");
        aLabelVitesse.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        add(aLabelVitesse, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 40, 20));
        
    }//GEN-END:initComponents

    private void aZoneTexteVitesseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aZoneTexteVitesseActionPerformed
        int lValeur = Integer.parseInt(evt.getActionCommand());
        
        if ((lValeur >= 10) || (lValeur == 0)){
            aLabelVitesse.setText(""+lValeur);
            aInit.asgnVitesseEtoiles(lValeur);
        }
    }//GEN-LAST:event_aZoneTexteVitesseActionPerformed

    public int reqVitesse() {
        int lValeur = Integer.parseInt(aLabelVitesse.getText());
        return lValeur;
    }
        
    private void aZoneTexteEtoilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aZoneTexteEtoilesActionPerformed
        int lValeur = Integer.parseInt(evt.getActionCommand());
        
        if ((lValeur >= 0) && (lValeur <= 1000)) {
            aLabelEtoiles.setText(""+lValeur);
            aInit.asgnNbEtoiles(lValeur);
            
            if (lValeur == 0) {
                aLabelVitesse.setText("0");
                aZoneTexteVitesse.setText("0");
                aZoneTexteVitesse.setEnabled(false);
            } else if (aZoneTexteVitesse.isEnabled() == false) {
                aLabelVitesse.setText("50");
                aZoneTexteVitesse.setText("50");
                aZoneTexteVitesse.setEnabled(true);
                aInit.asgnVitesseEtoiles(50);
            }
        }
    }//GEN-LAST:event_aZoneTexteEtoilesActionPerformed

    public int reqNbEtoiles() {
        int lValeur = Integer.parseInt(aLabelEtoiles.getText());
        return lValeur;
    }

    private void aZoneTextePlaneteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aZoneTextePlaneteActionPerformed
        int lValeur = Integer.parseInt(evt.getActionCommand());
        
        if ((lValeur >= 4*aNbJoueur) && (lValeur <= 500)) {
            aLabelPlanete.setText(""+lValeur);
        }
        
        aInit.reaffiche();
    }//GEN-LAST:event_aZoneTextePlaneteActionPerformed

    public int reqNbPlanetes() {
        int lValeur = Integer.parseInt(aLabelPlanete.getText());
        return lValeur;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLabelQPlanete;
    private javax.swing.JTextField aZoneTextePlanete;
    private javax.swing.JLabel aLabelPlanete;
    private javax.swing.JLabel aLabelQEtoiles;
    private javax.swing.JTextField aZoneTexteEtoiles;
    private javax.swing.JLabel aLabelEtoiles;
    private javax.swing.JLabel aLabelQVitesse;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField aZoneTexteVitesse;
    private javax.swing.JLabel aLabelVitesse;
    // End of variables declaration//GEN-END:variables

}
