/*
 * Donnees.java
 *
 * Created on 7 février 2002, 23:01
 */
import javax.swing.FocusManager;
import javax.swing.JOptionPane;
import java.util.StringTokenizer;
import java.awt.Color;
/**
 *
 * @author  Administrateur
 */
public class Donnees extends javax.swing.JPanel {
    private Espace aEspace;
    private Planete aPlanete;
    private boolean aEstDebute;
    
    /** Creates new form Donnees */
    public Donnees() {
        initComponents();
        
        aEstDebute = true;
    }
    
    public void asgnEstDebute(boolean pValeur) {
        aEstDebute = pValeur;
    }
    
    public void asgnEspace(Espace pEspace) {
        aEspace = pEspace;
    }
    
    public void arreteBoutonTermine() {
        aBoutonTermine.setEnabled(false);
    }
    
    public Planete reqPlaneteAffichee() {
        return aPlanete;
    }
    
    public void affiche() {
        if (aPlanete != null) {
            aLabelPlanete.setText("Plan\u00e8te : " + aPlanete.reqNom());
            if (aPlanete.reqProprietaire().reqEstJoueur()) {
                aLabelProprietaire.setText("Propri\u00e9taire : " + aPlanete.reqProprietaire().reqNom());
                aLabelProduction.setText("Production : " + aPlanete.reqProduction() + " (" + (int)(aPlanete.reqProduction()*aPlanete.reqProprietaire().reqBonusProduction()) + ")");
                aLabelVaisseaux.setText("Vaisseaux : " + aPlanete.reqNbVaisseau());
            } else {
                aLabelProprietaire.setText("Propri\u00e9taire : Inconnu"); // ou 'certains pirates inconnus..' ?
                aLabelProduction.setText("Production : ");
                aLabelVaisseaux.setText("Vaisseaux : ");
            }
            
            if(aPlanete.reqEstCommandee()) {
                aLabelPlanete.setForeground(new Color(255, 51, 51));
            } else {
                aLabelPlanete.setForeground(new Color(102, 102, 153));
            }
        }
    }
    
    public void affichePlanete(Planete pPlanete) {
        aPlanete = pPlanete;
        affiche();
    }
    
    public void afficheSource(Planete pPlanete) {
        aLabelDepart.setText("Depart : " + pPlanete.reqNom());
    }
    
    public void afficheDestination(Planete pPlanete) {
        aLabelDestination.setText("Destination : " + pPlanete.reqNom());
    }
    
    public void afficheDestination(String pNom) {
        aLabelDestination.setText("Destination : " + pNom);
    }
    public void reinitialise() {
        aLabelDepart.setText("Depart : ");
        aLabelDestination.setText("Destination : ");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        aLabelPlanete = new javax.swing.JLabel();
        aLabelProduction = new javax.swing.JLabel();
        aLabelDepart = new javax.swing.JLabel();
        aZoneTexteNbVaisseau = new javax.swing.JTextField();
        aLabelProprietaire = new javax.swing.JLabel();
        aLabelVaisseaux = new javax.swing.JLabel();
        aLabelDestination = new javax.swing.JLabel();
        aBoutonTermine = new javax.swing.JButton();
        
        setLayout(new java.awt.GridLayout(2, 0));
        
        setPreferredSize(new java.awt.Dimension(640, 40));
        setMinimumSize(new java.awt.Dimension(640, 40));
        aLabelPlanete.setText("Plan\u00e8te : ");
        add(aLabelPlanete);
        
        aLabelProduction.setText("Production : ");
        add(aLabelProduction);
        
        aLabelDepart.setText("Depart : ");
        add(aLabelDepart);
        
        aZoneTexteNbVaisseau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aZoneTexteNbVaisseauActionPerformed(evt);
            }
        });
        
        add(aZoneTexteNbVaisseau);
        
        aLabelProprietaire.setText("Propri\u00e9taire :");
        add(aLabelProprietaire);
        
        aLabelVaisseaux.setText("Vaisseaux : ");
        add(aLabelVaisseaux);
        
        aLabelDestination.setText("Destination : ");
        add(aLabelDestination);
        
        aBoutonTermine.setText("Termin\u00e9");
        aBoutonTermine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBoutonTermineActionPerformed(evt);
            }
        });
        
        add(aBoutonTermine);
        
    }//GEN-END:initComponents
    
    private void aZoneTexteNbVaisseauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aZoneTexteNbVaisseauActionPerformed
        if (aEstDebute) {
            String lTexte = evt.getActionCommand();
            if (lTexte.compareToIgnoreCase("save") == 0) {
                String lNom = JOptionPane.showInputDialog(null, "Dans quel fichier voulez-vous enregistrer la partie ?");
                aEspace.enregistre(lNom);
            } else if (lTexte.compareToIgnoreCase("asgnProprietaire") == 0) {
                if (!aEspace.trichageAsgnProprietaire()) System.out.println("Seulement des chiffres, et entiers !");
            } else if (lTexte.compareToIgnoreCase("avance") == 0) {
                if (!aEspace.trichageAvanceProprietaire()) System.out.println("Seulement des chiffres, et entiers !");
            } else if (lTexte.compareToIgnoreCase("recule") == 0) {
                if (!aEspace.trichageReculeProprietaire()) System.out.println("Seulement des chiffres, et entiers !");
            } else if (lTexte.toLowerCase().startsWith("concentrate")) {                
                StringTokenizer lChaineSeparee = new StringTokenizer(lTexte);
                String lToken = lChaineSeparee.nextToken();
                if (lChaineSeparee.hasMoreTokens()) {
                    String lPercent = lChaineSeparee.nextToken();
                    try {
                        double lDblPercent = Integer.parseInt(lPercent);
                        
                        if (lDblPercent > 1) { 
                            lDblPercent = 1; 
                        }
                        
                        if (lDblPercent < 0) {
                            lDblPercent = 0;
                        }
                        
                        aEspace.concentrate(lDblPercent);
                    } catch (java.lang.NumberFormatException pEvent) {
                        System.out.println("Valeure non double !");
                    }
                } else {
                    aEspace.concentrate(1.00);   
                }
            } else if (lTexte.toLowerCase().startsWith("envoie")) {                
                StringTokenizer lChaineSeparee = new StringTokenizer(lTexte);
                String lToken = lChaineSeparee.nextToken();
                if (lChaineSeparee.hasMoreTokens()) {
                    String lPercent = lChaineSeparee.nextToken();
                    try {
                        double lDblPercent = Double.parseDouble(lPercent);
                        
                        if (lDblPercent > 1) { 
                            lDblPercent = 1; 
                        }
                        
                        if (lDblPercent < 0) {
                            lDblPercent = 0;
                        }
                        
                        aEspace.envoieRectangle(lDblPercent);
                    } catch (java.lang.NumberFormatException pEvent) {
                        System.out.println("Valeure non double !");
                    }
                } else {
                    aEspace.envoieRectangle(1.00);   
                }
            } else if (lTexte.toLowerCase().startsWith("asgnprod")) {
                StringTokenizer lChaineSeparee = new StringTokenizer(lTexte);
                String lToken = lChaineSeparee.nextToken();
                if (lChaineSeparee.hasMoreTokens()) {
                    String lProd = lChaineSeparee.nextToken();
                    try {
                        int lIntProd = Integer.parseInt(lProd);
                        if (!aEspace.trichageAsgnProduction(lIntProd)) System.out.println("Seulement des chiffres, et entiers !");
                    } catch (java.lang.NumberFormatException pEvent) {
                        System.out.println("Seulement des chiffres, et entiers !");
                    }
                } else {
                    System.out.println("Seulement des chiffres, et entiers !");
                }
            } else if (lTexte.toLowerCase().startsWith("asgnnb")) {
                StringTokenizer lChaineSeparee = new StringTokenizer(lTexte);
                String lToken = lChaineSeparee.nextToken();
                if (lChaineSeparee.hasMoreTokens()) {
                    String lNbVaisseau = lChaineSeparee.nextToken();
                    try {
                        int lIntNbVaisseau = Integer.parseInt(lNbVaisseau);
                        if (!aEspace.trichageAsgnNbVaisseau(lIntNbVaisseau)) System.out.println("Seulement des chiffres, et entiers !");
                    } catch (java.lang.NumberFormatException pEvent) {
                        System.out.println("Seulement des chiffres, et entiers !");
                    }
                } else {
                    System.out.println("Seulement des chiffres, et entiers !");
                }
            } else if (lTexte.toLowerCase().startsWith("add")) {
                StringTokenizer lChaineSeparee = new StringTokenizer(lTexte);
                String lToken = lChaineSeparee.nextToken();
                if (lToken.compareToIgnoreCase("add") == 0) {
                    if (lChaineSeparee.hasMoreTokens()) {
                        String lNum = lChaineSeparee.nextToken();
                        if (lChaineSeparee.hasMoreTokens()) {
                            String lValeur = lChaineSeparee.nextToken();
                            try {
                                int lIntNum = Integer.parseInt(lNum);
                                double lDoubleValeur = Double.parseDouble(lValeur);
                                
                                if (!aEspace.trichageIncPropriete(lIntNum, lDoubleValeur)) System.out.println("Seulement des chiffres, et entiers !");
                            } catch (java.lang.NumberFormatException pEvent) {
                                System.out.println("Seulement des chiffres, et entiers !");
                            }
                        } else {
                            System.out.println("Seulement des chiffres, et entiers !");
                        }
                    } else {
                        System.out.println("Seulement des chiffres, et entiers !");
                    }
                } else if (lToken.compareToIgnoreCase("addFlotte") == 0) {
                    if (lChaineSeparee.hasMoreTokens()) {
                        String lNb = lChaineSeparee.nextToken();
                        if (lChaineSeparee.hasMoreTokens()) {
                            String lTemps = lChaineSeparee.nextToken();
                            try {
                                int lIntNb = Integer.parseInt(lNb);
                                int lIntTemps = Integer.parseInt(lTemps);
                                
                                if (!aEspace.trichageAddFlotte(lIntNb, lIntTemps)) System.out.println("Seulement des chiffres, et entiers !");
                            } catch (java.lang.NumberFormatException pEvent) {
                                System.out.println("Seulement des chiffres, et entiers !");
                            }
                        } else {
                            System.out.println("Seulement des chiffres, et entiers !");
                        }
                    } else {
                        System.out.println("Seulement des chiffres, et entiers !");
                    }
                } else {
                    System.out.println("Seulement des chiffres, et entiers !");
                }
            } else {
                try {
                    aEspace.envoieFlotte(Integer.parseInt(lTexte));
                } catch (java.lang.NumberFormatException pEvent) {
                    System.out.println("Seulement des chiffres, et entiers !");
                }
            }
            aZoneTexteNbVaisseau.setText("");
        }
    }//GEN-LAST:event_aZoneTexteNbVaisseauActionPerformed
    
    private void aBoutonTermineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBoutonTermineActionPerformed
        // On a clické le bouton Terminé
        if (aEstDebute) {
            aEspace.avanceJoueur();
            aZoneTexteNbVaisseau.setText("");
            
            if (FocusManager.isFocusManagerEnabled()) {
                FocusManager lFocus = FocusManager.getCurrentManager();
                lFocus.focusPreviousComponent(aBoutonTermine);
            } else {
                System.out.println("Pas de focus manager .. ");
            }
        }
    }//GEN-LAST:event_aBoutonTermineActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLabelPlanete;
    private javax.swing.JLabel aLabelProduction;
    private javax.swing.JLabel aLabelDepart;
    private javax.swing.JTextField aZoneTexteNbVaisseau;
    private javax.swing.JLabel aLabelProprietaire;
    private javax.swing.JLabel aLabelVaisseaux;
    private javax.swing.JLabel aLabelDestination;
    private javax.swing.JButton aBoutonTermine;
    // End of variables declaration//GEN-END:variables
    
    public void libereRessources() {
        aPlanete = null;
        aEspace = null;
    }
}
