/*
 * FenetreChat.java
 *
 * Created on 16 février 2002, 17:51
 */

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author  Administrateur
 */
public class FenetreChat extends javax.swing.JPanel {
    ZoneIP aZoneIP;
    
    
    /** Creates new form FenetreChat */
    public FenetreChat() {
        initComponents();
        
        aZoneIP = new ZoneIP();
        aScrollPaneIP.add(aZoneIP);
        
        add(aZoneIP);
    }
    
    public void additionne(Additionnable pAdditionnable) {
        aZoneIP.additionne(pAdditionnable);
        
        aScrollPaneIP.resize(aZoneIP.getSize());
        
        System.out.println("SP : " + aScrollPaneIP.getSize());
        System.out.println("ZB : " + aZoneIP.getSize() + ", " + aZoneIP.getPreferredSize() + ", " + aZoneIP.getMinimumSize());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        aZoneEcriture = new javax.swing.JTextField();
        aZoneLecture = new javax.swing.JTextField();
        aScrollPaneIP = new javax.swing.JScrollPane();
        
        jMenuItem1.setText("Item");
        jPopupMenu1.add(jMenuItem1);
        
        setLayout(new java.awt.BorderLayout());
        
        add(aZoneEcriture, java.awt.BorderLayout.SOUTH);
        
        aZoneLecture.setEditable(false);
        add(aZoneLecture, java.awt.BorderLayout.CENTER);
        
        aScrollPaneIP.setPreferredSize(new java.awt.Dimension(100, 100));
        aScrollPaneIP.setMinimumSize(new java.awt.Dimension(100, 100));
        add(aScrollPaneIP, java.awt.BorderLayout.EAST);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField aZoneEcriture;
    private javax.swing.JTextField aZoneLecture;
    private javax.swing.JScrollPane aScrollPaneIP;
    // End of variables declaration//GEN-END:variables

    public static void main(String pArgs[]) {
        JFrame lApplication = new JFrame("Espace MiniGame");
        
        PanneauIPMaitre lPanneauIPMaitre = new PanneauIPMaitre();
        lPanneauIPMaitre.asgnIP("127.0.0.1:0000");
        lPanneauIPMaitre.additionneNom("PIBM");
        lPanneauIPMaitre.additionneNom("UMBRO_GIRL");
        
        PanneauIP lPanneauIP = new PanneauIP();
        lPanneauIP.asgnIP("215.243.3.134:0001");
        lPanneauIP.additionneNom("Patou");
        lPanneauIP.additionneNom("Annie");
        lPanneauIP.additionneNom("Louif");
        
        FenetreChat lFenetre = new FenetreChat();
        lFenetre.additionne(lPanneauIPMaitre);
        lFenetre.additionne(lPanneauIP);
        
        lApplication.getContentPane().add(lFenetre, BorderLayout.CENTER);
        lApplication.addWindowListener
        (
        new WindowAdapter() {
            public void windowClosing(WindowEvent pEvenement) {
                System.exit(0);
            }
        }
        );
        
        lApplication.setSize(290, 265);
        lApplication.show();
    }
}
