/*
 * Statistiques.java
 *
 * Created on 7 février 2002, 23:27
 */

/**
 *
 * @author  Administrateur
 */
public class Statistiques extends javax.swing.JPanel {

    /** Creates new form Statistiques */
    public Statistiques() {
        initComponents();
    }
    
    public void affiche(Proprietaire pProprietaire) {
        aLabelJoueur.setText("Joueur : " + pProprietaire.reqNom());
        aLabelNbPlanete.setText("Nb Planetes : " + pProprietaire.reqNbPlanete());
        aLabelNbFlotte.setText("Nb Flottes : " + pProprietaire.reqNbFlotte());
        aLabelNbVaisseaux.setText("Nb Vaisseaux : " + pProprietaire.reqNbVaisseau() + " (" + pProprietaire.reqNbProduction() + ")");
        
        String lBonusAttaque = String.valueOf(pProprietaire.reqBonusAttaque());
        String lBonusDefense = String.valueOf(pProprietaire.reqBonusDefense());
        String lBonusProduction = String.valueOf(pProprietaire.reqBonusProduction());
        String lBonusDeplacement = String.valueOf(pProprietaire.reqBonusDeplacement());

        if (lBonusAttaque.length() > 4) { lBonusAttaque = lBonusAttaque.substring(0,4); }
        if (lBonusDefense.length() > 4) { lBonusDefense = lBonusDefense.substring(0,4); }
        if (lBonusProduction.length() > 4) { lBonusProduction = lBonusProduction.substring(0,4); }
        if (lBonusDeplacement.length() > 4) { lBonusDeplacement = lBonusDeplacement.substring(0,4); }
        
        aLabelAttaque.setText("Attaque : " + lBonusAttaque);
        aLabelDefense.setText("Defense : " + lBonusDefense);
        aLabelProduction.setText("Production : " + lBonusProduction);
        aLabelDeplacement.setText("Deplacement : " + lBonusDeplacement);
    }

    public void refresh() {
        aLabelJoueur.setText("");
        aLabelJoueur.setText("Joueur : ");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        aLabelJoueur = new javax.swing.JLabel();
        aLabelNbPlanete = new javax.swing.JLabel();
        aLabelNbFlotte = new javax.swing.JLabel();
        aLabelNbVaisseaux = new javax.swing.JLabel();
        aLabelAttaque = new javax.swing.JLabel();
        aLabelDefense = new javax.swing.JLabel();
        aLabelProduction = new javax.swing.JLabel();
        aLabelDeplacement = new javax.swing.JLabel();
        
        setLayout(new java.awt.GridLayout(2, 0));
        
        setPreferredSize(new java.awt.Dimension(640, 40));
        setMinimumSize(new java.awt.Dimension(640, 40));
        aLabelJoueur.setText("Joueur : ");
        add(aLabelJoueur);
        
        aLabelNbPlanete.setText("Nb Planetes : ");
        add(aLabelNbPlanete);
        
        aLabelNbFlotte.setText("Nb Flottes : ");
        add(aLabelNbFlotte);
        
        aLabelNbVaisseaux.setText("Nb Vaisseaux : ");
        add(aLabelNbVaisseaux);
        
        aLabelAttaque.setText("Attaque : ");
        add(aLabelAttaque);
        
        aLabelDefense.setText("Defense : ");
        add(aLabelDefense);
        
        aLabelProduction.setText("Production : ");
        add(aLabelProduction);
        
        aLabelDeplacement.setText("Deplacement : ");
        add(aLabelDeplacement);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLabelJoueur;
    private javax.swing.JLabel aLabelNbPlanete;
    private javax.swing.JLabel aLabelNbFlotte;
    private javax.swing.JLabel aLabelNbVaisseaux;
    private javax.swing.JLabel aLabelAttaque;
    private javax.swing.JLabel aLabelDefense;
    private javax.swing.JLabel aLabelProduction;
    private javax.swing.JLabel aLabelDeplacement;
    // End of variables declaration//GEN-END:variables

}
